### ISSUE TITLE
建议加入Poe支持

### ISSUE THREAD

**Issue by pamaforce** [Soulter/AstrBot#126]

**Comment by Soulter** [comment]
好，未来几天会在[llms插件](https://github.com/Soulter/llms)上更新

**Comment by pamaforce** [comment]
> 好，未来几天会在[llms插件](https://github.com/Soulter/llms)上更新

请问有进展吗🤓

**Comment by Soulter** [comment]
> > 好，未来几天会在[llms插件](https://github.com/Soulter/llms)上更新
> 
> 请问有进展吗🤓

抱歉最近有点忙，刚刚试着使用一些其他的Poe-API接入了一下Poe，但是处于不可用的状态，目前还是先使用ChatGPT、HuggingChat、Claude、Bard吧

**Comment by pamaforce** [comment]
> > > 好，未来几天会在[llms插件](https://github.com/Soulter/llms)上更新
> > 
> > 
> > 请问有进展吗🤓
> 
> 抱歉最近有点忙，刚刚试着使用一些其他的Poe-API接入了一下Poe，但是处于不可用的状态，目前还是先使用ChatGPT、HuggingChat、Claude、Bard吧

嗯，我也最近了解到了9月18日由于poe的api更新了导致poe-api项目不可用了。这个项目是我目前找到最好的QQ频道机器人接入AI的项目了，感谢您的维护！
