### ISSUE TITLE
支持在配置文件中设置默认人格

### ISSUE THREAD

**Issue by sekaom** [Soulter/AstrBot#139]
对自定义人格的有要求，但是每次重启后又需要手动设置到自定义的人格。有时候会因为一些问题不得不重启后又要手动设置  
因此希望可以添加对默认人格的设置

**Comment by Soulter** [comment]
已支持。

更新并启动后，在 cmd_config 中填写 default_personality_str 那一项可以设置人格文本，再次重启即生效。
