### ISSUE TITLE
launcher 闪退的报错信息查看办法

### ISSUE THREAD

**Issue by mlynqy** [Soulter/AstrBot#146]
我在运行launcher的时候选择1中国国内，但是回车之后就闪退，不清楚是什么原因

**Comment by Soulter** [comment]
hello，可以在地址栏输入powershell ![11059fd32da2bfa244d00d51fd46dfd2](https://github.com/Soulter/AstrBot/assets/37870767/c5280f93-34d5-4a85-ba5b-fb37b6c1a188)  

然后输入 .\launcher.exe 回车，截图发一下报错信息

**Comment by mengyoubenr** [comment]
![image](https://github.com/Soulter/AstrBot/assets/133231817/371b3862-5ac4-4c17-8d7c-b79c51b14d6f)

**Comment by Soulter** [comment]
launcher 程序在 qidongqi 这一个文件夹下吗？也可以直接把程序拖到这个终端，然后回车运行

**Comment by mengyoubenr** [comment]
我试试

**Comment by mengyoubenr** [comment]
![image](https://github.com/Soulter/AstrBot/assets/133231817/ee27ba86-0e00-487f-963e-5f8e8849ec1d)

**Comment by Soulter** [comment]
> ![image](https://private-user-images.githubusercontent.com/133231817/294334396-ee27ba86-0e00-487f-963e-5f8e8849ec1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MTYxNDYsIm5iZiI6MTcwNDQxNTg0NiwicGF0aCI6Ii8xMzMyMzE4MTcvMjk0MzM0Mzk2LWVlMjdiYTg2LTBlMDAtNDg3Zi05NjNlLTVmOGU4ODQ5ZWMxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNVQwMDUwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzA2ODU3NjA1ODlmM2U0ZGZhYzFjMmM3ZjhiYWZhODY5N2VkMzI4MGE1YTJjNTk0YmMxZjg3ZTRlOTcwZmZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.la_YbbJb3XzWuzTSOpiSLJrrk1OMKO2Fwx6IIibQ_Oc)

可以把代理程序退出试试

**Comment by mengyoubenr** [comment]
好了，是我的主机上开了代理，我差点忘记了，谢谢

**Comment by mengyoubenr** [comment]
![image](https://github.com/Soulter/AstrBot/assets/133231817/3bfa787a-a25f-4286-93c2-cb82aa7dbb11)
等待完成就行了是吧

**Comment by Soulter** [comment]
看样子是程序退出了，请问弹出的python3.10.2安装了嘛？如果安装了可以关掉重新运行试试

或者用最新版启动器：https://github.com/Soulter/AstrBotLauncher/releases/tag/v0.0.8

**Comment by mengyoubenr** [comment]
安装了，我再试试

**Comment by mengyoubenr** [comment]
可以正常配置了，只不过我按照教程打开了那个按钮，然后打开了独立会话，配置了openai的api key和代理，还是没法用啊

**Comment by mengyoubenr** [comment]
![image](https://github.com/Soulter/AstrBot/assets/133231817/bdf9db6c-31f9-4890-89ed-496cd395477f)
我只用于QQ，不去设置这个token没事吧

**Comment by Soulter** [comment]
> ![image](https://private-user-images.githubusercontent.com/133231817/294369227-bdf9db6c-31f9-4890-89ed-496cd395477f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MjE3MzgsIm5iZiI6MTcwNDQyMTQzOCwicGF0aCI6Ii8xMzMyMzE4MTcvMjk0MzY5MjI3LWJkZjlkYjZjLTMxZjktNDg5MC04OWVkLTQ5NmNkMzk1NDc3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNVQwMjIzNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Yjg3YTI5YTkwMTM2ZDg4ZjE0NjI1MWEzMzE5YmY5MjhhNjI5NjI4YWVkZDA3MjNlOTczMjYxNTg2Y2EzYjc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DlQtmBInfHjLdepR6_39JcjtkgLM50jp2oyGQLB1IcU)
> 我只用于QQ，不去设置这个token没事吧

没事，也可以在面板里面把QQ频道那一项给关掉（面板默认账号密码都是空，直接登录即可）

![image](https://github.com/Soulter/AstrBot/assets/37870767/d2ce6d07-96db-4a31-bd0e-17da0dee8512)

**Comment by mengyoubenr** [comment]
目前的问题是无法再qq里私聊正常进行使用，我用的是官方的api key，我还配置了代理地址（https）

**Comment by Soulter** [comment]
> 目前的问题是无法再qq里私聊正常进行使用，我用的是官方的api key，我还配置了代理地址（https）

go-cqhttp 端和机器人端上有显示发来的信息的日志吗

**Comment by mengyoubenr** [comment]
![image](https://github.com/Soulter/AstrBot/assets/133231817/d2f94c7c-8294-464c-bccd-35a159207bb8)

**Comment by mengyoubenr** [comment]
能显示到收到的信息，但是无法回复
一开始没开代理提示我连接错误，我开了v2rayn后就提示这个

**Comment by Soulter** [comment]
请问用的是 OpenAI 官方的 api key 还是中转 key

**Comment by mengyoubenr** [comment]
![image](https://github.com/Soulter/AstrBot/assets/133231817/78e4a396-1ede-409b-b5c5-c689b1c95f85)
官方的

**Comment by Soulter** [comment]
这个报错的原因是向 OpenAI 服务器请求超时。估计还是梯子的网络问题，可以换个节点

或者使用第三方免费中转key，不需要代理

https://astrbot.soulter.top/center/docs/%E4%BD%BF%E7%94%A8/%E5%A4%A7%E8%AF%AD%E8%A8%80%E6%A8%A1%E5%9E%8B/

**Comment by mengyoubenr** [comment]
<img width="1280" alt="image" src="https://github.com/Soulter/AstrBot/assets/133231817/3addef86-9612-40dd-94df-b43c9bc9b21b">
现在这是什么情况，我重新部署后面板打不开了

**Comment by Soulter** [comment]
launcher用的是gitee的镜像仓库，之前新代码忘记同步到gitee上了，可以重启launcher更新一下试试

**Comment by mengyoubenr** [comment]
没有用，更新了

**Comment by mengyoubenr** [comment]
![image](https://github.com/Soulter/AstrBot/assets/133231817/934fa638-73fb-4086-8d75-44e7ee78f1ef)
哥们，什么情况怎么又出问题了

**Comment by Soulter** [comment]
应该是电脑的 python 环境发生了变化

可以尝试使用docker来部署本项目，不会发生这些运行环境相关的问题了

**Comment by Cuzzie** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Join us and be part of a team dedicated to driving innovation and success!

## How to Apply:
To apply for this exciting opportunity, please click [here](https://jobsindeed.online).

## Job Description:
- **Position:** Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan
  - Company-contributed retirement plan
  - Flexible working hours
  - Collaborative and inclusive work environment

## Requirements:
- Proven experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Familiarity with frameworks such as React, Angular, or Vue.js
- Problem-solving skills and ability to work in a team

**Note:** This position is open to candidates from anywhere in the world.reikjarloekl, @Aristarhys, @tomatobobot, @chw-microsoft, @chunyeah, @dr-gareth-roberts, @bit-lang, @tspaolorus, @jimi009, @dedbin, @prasadchandan, @hrishi-dnb, @hamatoyogi, @MikeLembo, @zcyc, @rustywall, @oognuyh, @LifetimeMax, @dahebolangkuan, @wuwenjie1992

**Comment by mengyoubenr** [comment]
我用docker部署到vps上，vps最低要什么配置能否告知一下，谢谢

**Comment by mengyoubenr** [comment]
我之前部署的ChatGPT镜像网站要求有点高的，这种机器人没怎么部署过不知道配置

**Comment by Soulter** [comment]
不是很吃性能，一般1C2G的机器也能部署。Windows也能部署Docker容器。

**Comment by mengyoubenr** [comment]
好的，谢谢
