### ISSUE TITLE
你好，再launch的时候出现上述报错

### ISSUE THREAD

**Issue by tesimeiyoulaa** [Soulter/AstrBot#148]
![PixPin_2024-01-22_16-28-18](https://github.com/Soulter/AstrBot/assets/104752007/72d629fc-cb6b-4478-bc67-801510434b76)
请问大大这个如何解决呢

**Comment by Soulter** [comment]
抱歉回得有点晚。看起来是你之前装过Flask库，但是版本太老了。可以用
```
python3 -m pip install flask --upgrade
```
升级一下
