### ISSUE TITLE
画图直接报错

### ISSUE THREAD

**Issue by dqzboy** [Soulter/AstrBot#151]
对话没问题，画图直接返回报错
<img width="862" alt="image" src="https://github.com/Soulter/AstrBot/assets/42825450/2bde8faa-e7b1-44d5-9f19-aad896bc56c4">

**Comment by dqzboy** [comment]
而且还有一个问题就是，我把上面的问题直接复制扔给机器人就直接不回复，并且服务日志都没有显示接收到了这个信息
<img width="805" alt="image" src="https://github.com/Soulter/AstrBot/assets/42825450/fbd2ded4-5935-4190-8432-b3f78c3d406a">

**Comment by TBMnaitang** [comment]
作者设置的默认绘画模型是dall-e 3，一般的api只能使用dall-e 2，去配置界面修改成dall-e 2绘画模型应该就能解决了

**Comment by dqzboy** [comment]
> 作者设置的默认绘画模型是dall-e 3，一般的api只能使用dall-e 2，去配置界面修改成dall-e 2绘画模型应该就能解决了

应该不是这个问题，我的是支持dall-e 3；/v1/images/generations 画图的接口 我在第三方的web平台测试都可以返回的

**Comment by Soulter** [comment]
> 对话没问题，画图直接返回报错 <img alt="image" width="862" src="https://private-user-images.githubusercontent.com/42825450/304000137-2bde8faa-e7b1-44d5-9f19-aad896bc56c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NDQ4NjUsIm5iZiI6MTcwNzc0NDU2NSwicGF0aCI6Ii80MjgyNTQ1MC8zMDQwMDAxMzctMmJkZThmYWEtZTdiMS00NGQ1LTlmMTktYWFkODk2YmM1NmM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDEzMjkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzMWMyNmU2YzM0NWM4MjJmMDg1YWNhYjdhYWEwNDhjZTExNDhlYzdjYmI1MDE1YWVmODgwZjMxMmY0ODFhMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Nd6SNZ4rCB-SbBu1xOYnAc5iR7q0s-6jOCuUZA-PtFY">

看报错应该是连接问题。配置一下代理试试？

**Comment by Soulter** [comment]
> 而且还有一个问题就是，我把上面的问题直接复制扔给机器人就直接不回复，并且服务日志都没有显示接收到了这个信息 <img alt="image" width="805" src="https://private-user-images.githubusercontent.com/42825450/304001181-fbd2ded4-5935-4190-8432-b3f78c3d406a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NDQ4NjUsIm5iZiI6MTcwNzc0NDU2NSwicGF0aCI6Ii80MjgyNTQ1MC8zMDQwMDExODEtZmJkMmRlZDQtNTkzNS00MTkwLTg0MzItYjNmNzhjM2Q0MDZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDEzMjkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNjhiZGY3MTgzMWY0Yjc2MGJkMzAwOTg1MGExZTI4MjAyNGQ1ZDY0OThmYzU0NWNhNTk5MzA5OWYyZGZhMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A6xE8kaCMYAMBwNvnX3AVkbdqcGn0l0gJuhAjWDUvZc">

这个原因应该是消息被QQ频道屏蔽了（可能带有链接等违规信息🫤），不是本项目的问题

**Comment by dqzboy** [comment]
> > 而且还有一个问题就是，我把上面的问题直接复制扔给机器人就直接不回复，并且服务日志都没有显示接收到了这个信息 <img alt="image" width="805" src="https://private-user-images.githubusercontent.com/42825450/304001181-fbd2ded4-5935-4190-8432-b3f78c3d406a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NDQ4NjUsIm5iZiI6MTcwNzc0NDU2NSwicGF0aCI6Ii80MjgyNTQ1MC8zMDQwMDExODEtZmJkMmRlZDQtNTkzNS00MTkwLTg0MzItYjNmNzhjM2Q0MDZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDEzMjkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNjhiZGY3MTgzMWY0Yjc2MGJkMzAwOTg1MGExZTI4MjAyNGQ1ZDY0OThmYzU0NWNhNTk5MzA5OWYyZGZhMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A6xE8kaCMYAMBwNvnX3AVkbdqcGn0l0gJuhAjWDUvZc">
> 
> 这个原因应该是消息被QQ频道屏蔽了（可能带有链接等违规信息🫤），不是本项目的问题

哦哦 明白了

**Comment by dqzboy** [comment]
测试下其他的qq频道的项目，没有出现上面的问题，可以正常画图以及回答上面的提问，使用测试的项目：https://github.com/rimdl/QPDBot

**Comment by Soulter** [comment]
> 测试下其他的qq频道的项目，没有出现上面的问题，可以正常画图以及回答上面的提问，使用测试的项目：https://github.com/rimdl/QPDBot

好的，我排查一下

**Comment by dqzboy** [comment]
> > 测试下其他的qq频道的项目，没有出现上面的问题，可以正常画图以及回答上面的提问，使用测试的项目：https://github.com/rimdl/QPDBot
> 
> 好的，我排查一下

辛苦，大佬

**Comment by Soulter** [comment]
似乎的确是QQ频道在私聊下屏蔽了带有链接的信息，可以提供一下和 QPDBot 关于这类信息的私聊截图吗

<img width="356" alt="image" src="https://github.com/Soulter/AstrBot/assets/37870767/a3693cc6-8a03-4aa7-b7a6-a02cdc56c064">

<img width="300" alt="image" src="https://github.com/Soulter/AstrBot/assets/37870767/00682b42-5aa5-435e-a246-714f7eb35d88">

**Comment by Soulter** [comment]
看了一下 QPDBot，似乎没有 OpenAI API 风格的相关生成图像的方法，只有 Gemini 的生成图像方法，请问你是使用 Gemini 生成图像吗

**Comment by dqzboy** [comment]
> 似乎的确是QQ频道在私聊下屏蔽了带有链接的信息，可以提供一下和 QPDBot 关于这类信息的私聊截图吗
> 
> <img alt="image" width="356" src="https://private-user-images.githubusercontent.com/37870767/305351403-a3693cc6-8a03-4aa7-b7a6-a02cdc56c064.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMTk5MzUsIm5iZiI6MTcwODIxOTYzNSwicGF0aCI6Ii8zNzg3MDc2Ny8zMDUzNTE0MDMtYTM2OTNjYzYtOGEwMy00YWE3LWI3YTYtYTAyY2RjNTZjMDY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDAxMjcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiZDNlMDc1NTA4MjkyYjRmYTkzYTA5Yzg5MzQ1N2E2OGZlZmQ5NGY5ODVhMzg5ZDMwNDliNTg1NjJjMTQ1MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.53aHD-KFIPh5zYaqbScheD6Z0gHE8RrMXBoxmYOkfZo"> <img alt="image" width="300" src="https://private-user-images.githubusercontent.com/37870767/305351623-00682b42-5aa5-435e-a246-714f7eb35d88.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMTk5MzUsIm5iZiI6MTcwODIxOTYzNSwicGF0aCI6Ii8zNzg3MDc2Ny8zMDUzNTE2MjMtMDA2ODJiNDItNWFhNS00MzVlLWEyNDYtNzE0ZjdlYjM1ZDg4LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOFQwMTI3MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDY5ZGExY2Q1ZGYwMjM2NWM5NzJmMzliOGJhZjg0N2JiM2JkOWRiZmRjYzFmYzcyZWQ4ODUxMzExNjA4YTUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2EbKFZo5bgU3K5yEw0eXe-ZmwmK-MHWcVZ4SEyubz_g">

QPDBot不支持私聊，群聊带连接的会回复，然后QPDBot图片返回的是图片链接；然后图片返回的接口是支持openai文生图标准接口

**Comment by dqzboy** [comment]
> 看了一下 QPDBot，似乎没有 OpenAI API 风格的相关生成图像的方法，只有 Gemini 的生成图像方法，请问你是使用 Gemini 生成图像吗

这是使用QPDBot在频道里面进行测试的截图，图像返回的是图片链接
![图片_20240218140440](https://github.com/Soulter/AstrBot/assets/42825450/4eb20b62-7461-42aa-a8a0-86f448faa679)

**Comment by dqzboy** [comment]
又测试了一下AstrBot和QPDbot，私聊带连接都不行，不是项目问题，抱歉。画图超时的问题，找到原因了，好像在频道里 让机器人画 xxx 的时候，会把 画 这个词给屏蔽掉，最后后端接收到的只有 xxx；艾特机器人时，多打一个画字就可以了，这个是否可以优化一下呢

**Comment by Soulter** [comment]
> 又测试了一下AstrBot和QPDbot，私聊带连接都不行，不是项目问题，抱歉。画图超时的问题，找到原因了，好像在频道里 让机器人画 xxx 的时候，会把 画 这个词给屏蔽掉，最后后端接收到的只有 xxx；艾特机器人时，多打一个画字就可以了，这个是否可以优化一下呢

画这个字就相当于指令了，如果不去掉画这个字的话，生成的图片貌似风格都是油画

**Comment by dqzboy** [comment]
> > 又测试了一下AstrBot和QPDbot，私聊带连接都不行，不是项目问题，抱歉。画图超时的问题，找到原因了，好像在频道里 让机器人画 xxx 的时候，会把 画 这个词给屏蔽掉，最后后端接收到的只有 xxx；艾特机器人时，多打一个画字就可以了，这个是否可以优化一下呢
> 
> 画这个字就相当于指令了，如果不去掉画这个字的话，生成的图片貌似风格都是油画

这个应该是看第三方代理了吧，我用的这个第三方代理没有这个问题
