### ISSUE TITLE
只能主动连接吗

### ISSUE THREAD

**Issue by tamakyi** [Soulter/AstrBot#152]
因为某些情况我的环境只能被动websocket，但是好像没办法配置，只能由astr连接到cqhttp吗？

**Comment by Soulter** [comment]
目前只支持主动连接到 cqhttp，近期可以支持一下被动连接

**Comment by tamakyi** [comment]
> 目前只支持主动连接到 cqhttp，近期可以支持一下被动连接

👍赞！

**Comment by tamakyi** [comment]
> 目前只支持主动连接到 cqhttp，近期可以支持一下被动连接

还有个事情想请教下，是不兼容shamrock吗？我无论是本地部署还是远程部署shamrock填写配置的时候都会提示与go-cqhttp通信失败（http和websocket均正常）

**Comment by Soulter** [comment]
cqhttp和shamrock不是一个东西吧，目前还没适配shamrock

**Comment by tamakyi** [comment]
> cqhttp和shamrock不是一个东西吧，目前还没适配shamrock

哦，那我可能看错了，应该兼容的是onebot

**Comment by Soulter** [comment]
这两天会兼容一下这个

**Comment by Soulter** [comment]
> > 目前只支持主动连接到 cqhttp，近期可以支持一下被动连接
> 
> 还有个事情想请教下，是不兼容shamrock吗？我无论是本地部署还是远程部署shamrock填写配置的时候都会提示与go-cqhttp通信失败（http和websocket均正常）

噢我理解错了，应该是兼容的，端口有配对嘛

**Comment by tamakyi** [comment]
> > > 目前只支持主动连接到 cqhttp，近期可以支持一下被动连接
> > 
> > 还有个事情想请教下，是不兼容shamrock吗？我无论是本地部署还是远程部署shamrock填写配置的时候都会提示与go-cqhttp通信失败（http和websocket均正常）
> 
> 噢我理解错了，应该是兼容的，端口有配对嘛

端口倒是没问题，因为相同配置相同环境下我使用其他bot是能够正常连接并使用的。

**Comment by RockChinQ** [comment]
现在用的连接gocq的框架是nakuru，nakuru连接shamrock会有问题

**Comment by tamakyi** [comment]
> 现在用的连接gocq的框架是nakuru，nakuru连接shamrock会有问题

我也在使用您的QChatGPT项目，但是昨天试了一下使用nakuru连接到shamrock貌似是正常的，能正常通信

**Comment by RockChinQ** [comment]
> > 现在用的连接gocq的框架是nakuru，nakuru连接shamrock会有问题
> 
> 我也在使用您的QChatGPT项目，但是昨天试了一下使用nakuru连接到shamrock貌似是正常的，能正常通信

nakuru之前测试，群聊消息会有问题，3.0会支持aiocqhttp连接onebot

**Comment by tamakyi** [comment]
> > > 现在用的连接gocq的框架是nakuru，nakuru连接shamrock会有问题
> > 
> > 我也在使用您的QChatGPT项目，但是昨天试了一下使用nakuru连接到shamrock貌似是正常的，能正常通信
> 
> nakuru之前测试，群聊消息会有问题，3.0会支持aiocqhttp连接onebot

我只有在私聊测试，估计没有触发🙃

**Comment by Soulter** [comment]
有个bug，如果修改了默认端口（5700和6700）的话，虽然连接成功了，依然会出现连接失败的提示。这个项目对onebot的适配目前也是使用nakuru的，应该也和qchatgpt一样私聊可以群聊不行

**Comment by tamakyi** [comment]
> 有个bug，如果修改了默认端口（5700和6700）的话，虽然连接成功了，依然会出现连接失败的提示。这个项目对onebot的适配目前也是使用nakuru的，应该也和qchatgpt一样私聊可以群聊不行

哦哦，明白了。
