### ISSUE TITLE
回复代码块，显示不友好。

### ISSUE THREAD

**Issue by animeic** [Soulter/AstrBot#154]
![微信截图_20240312162953](https://github.com/Soulter/AstrBot/assets/84631372/dcb8ff9e-55fc-4212-9a2b-0a1bbeec8be0)

**Comment by Soulter** [comment]
目前可以使用转图片功能，在配置-通用中，启用消息转图片
<img width="410" alt="image" src="https://github.com/Soulter/AstrBot/assets/37870767/276ddaba-9aad-49ee-b37b-3c770006aa41">

这会使用PIL模拟渲染一个markdown格式的文本。不过可能渲染效果不是最好的，这个之后会优化一下。
