### ISSUE TITLE
发起对话时报错：[System/ERROR] 未找到平台 qqchan 的实例。

### ISSUE THREAD

**Issue by linxp001** [Soulter/AstrBot#155]
![image](https://github.com/Soulter/AstrBot/assets/75927451/0e664d7b-5ed4-45c6-9d62-6006842b509b)

拉了最新镜像也不好使。

**Comment by linxp001** [comment]
![image](https://github.com/Soulter/AstrBot/assets/75927451/47c4acef-5289-4ede-bf59-978da332bfc9)

**Comment by Soulter** [comment]
你好，我排查后发现确实有这个问题。刚刚提交的 commit 已经修复此报错，可以更新试试。

可以在面板右上角更新按钮更新。

**Comment by linxp001** [comment]
好使了，谢谢老板。
