### ISSUE TITLE
私聊正常，群聊报错：AttributeError: 'coroutine' object has no attribute 'message'

### ISSUE THREAD

**Issue by linxp001** [Soulter/AstrBot#156]
![image](https://github.com/Soulter/AstrBot/assets/75927451/ef3c7212-e4bd-4dbe-bc94-13223319be0d)

**Comment by linxp001** [comment]
私聊好使，以为没问题了，结果发现在群里@机器人发消息会报错……

**Comment by Soulter** [comment]
可以试试非画画指令是否正常

**Comment by linxp001** [comment]
确实，我私聊时发画画也会报错，但之前都可以用啊，为啥现在报错了……
我这个就是画画机器人，以前都没问题的啊

**Comment by linxp001** [comment]
![image](https://github.com/Soulter/AstrBot/assets/75927451/1bf86fc9-d0a3-4f64-9b42-2e0a54f9c655)
之前都好使的，都是用的咱们的程序

**Comment by linxp001** [comment]
群聊时非画画指令也都正常

**Comment by Soulter** [comment]
刚刚提交的代码已经修复这个问题了，可以更新试试。谢谢！

**Comment by linxp001** [comment]
![image](https://github.com/Soulter/AstrBot/assets/75927451/4397b626-26f2-4de7-baf8-64908720253f)辛苦老板了
