### ISSUE TITLE
能否增加回对New Bing 的支持

### ISSUE THREAD

**Issue by maotuworkroom** [Soulter/AstrBot#158]
如题

**Comment by Soulter** [comment]
你好，最近没多关注 New Bing，New Bing 开放了第三方调用吗？

**Comment by maotuworkroom** [comment]
> Bing

你好，据我所知bing似乎一直以来都没有开放过官方调用好像。我的意思是能否支持类似这几个项目（具体项目链接位于后续评论）中的对new bing的支持，因为bing的信息时效性更强使用也趋于免费且此项目的图形化界面特别便于使用和管理，希望可以结合，谢谢！😊

**Comment by maotuworkroom** [comment]
> 你好，最近没多关注 New Bing，New Bing 开放了第三方调用吗？

https://github.com/lss233/chatgpt-mirai-qq-bot

**Comment by maotuworkroom** [comment]
> 你好，最近没多关注 New Bing，New Bing 开放了第三方调用吗？

https://github.com/zhayujie/bot-on-anything

**Comment by maotuworkroom** [comment]
> > 你好，最近没多关注 New Bing，New Bing 开放了第三方调用吗？
> 
> https://github.com/lss233/chatgpt-mirai-qq-bot

我主要参考的是此项目

**Comment by maotuworkroom** [comment]
> 你好，最近没多关注 New Bing，New Bing 开放了第三方调用吗？

https://github.com/thx114/SDGPT
