### ISSUE TITLE
启动QQ频道机器人时出现错误, 原因如下: module 'botpy.message' has no attribute 'GroupMessage

### ISSUE THREAD

**Issue by xxynet** [Soulter/AstrBot#159]
使用windows launcher运行，启动时报错：启动QQ频道机器人时出现错误, 原因如下: module 'botpy.message' has no attribute 'GroupMessage

**Comment by Soulter** [comment]
用的 python 是电脑上自带的吗? 可以尝试更新一下 qq-botpy 这个库
