### ISSUE TITLE
程序闪退

### ISSUE THREAD

**Issue by zhouxiangwen328** [Soulter/AstrBot#165]
我将程序升级到最新版本以后程序启动时好像是无法打开requirements这个文件
https://github.com/Soulter/AstrBot/assets/163638679/d43fba54-9b59-47d5-827f-f26817eb2119

**Comment by zhouxiangwen328** [comment]
![Uploading Screenshot_20240526_180743.jpg…]()

**Comment by zhouxiangwen328** [comment]
[](url)

**Comment by zhouxiangwen328** [comment]
![Screenshot_20240526_180743](https://github.com/Soulter/AstrBot/assets/163638679/2e51cc8e-9145-45bd-9ecf-2661038d033a)

**Comment by Soulter** [comment]
问题已修复，请重新打开启动器然后选择更新项目。

**Comment by zhouxiangwen328** [comment]
![Screenshot_20240526_182657](https://github.com/Soulter/AstrBot/assets/163638679/a35272c8-b721-4bdd-9f52-5d9261ccb972)
程序一直这样子尝试多次

**Comment by zhouxiangwen328** [comment]
![Screenshot_20240526_182940](https://github.com/Soulter/AstrBot/assets/163638679/d652da96-feec-47e2-ae29-f6c3de5d4656)

**Comment by Soulter** [comment]
> ![Screenshot_20240526_182657](https://private-user-images.githubusercontent.com/163638679/333871727-a35272c8-b721-4bdd-9f52-5d9261ccb972.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MTk1NDksIm5iZiI6MTcxNjcxOTI0OSwicGF0aCI6Ii8xNjM2Mzg2NzkvMzMzODcxNzI3LWEzNTI3MmM4LWI3MjEtNGJkZC05ZjUyLTVkOTI2MWNjYjk3Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQxMDI3MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xN2E2ZmZhZWM3ZTUzNThlYzUwNTQyN2NhZjhhMjI2YmYzNzcxMTA0ZDBiMzRiZTgxZTNmMDU4ZjJlZWFkZTI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Oeiep2P5ezoFBwdOun2kvx4-KpDIiVeJQ5qwsg5EgyE) 程序一直这样子尝试多次

这里直接回车试试

**Comment by zhouxiangwen328** [comment]
![Screenshot_20240526_184032](https://github.com/Soulter/AstrBot/assets/163638679/9b343a44-bd46-428e-bcb1-1e19a5ea372f)
回车以后也有问题

**Comment by Soulter** [comment]
是一直没更新成功嘛？可以试一下将 QQChannelChatGPT 这个文件夹删掉

**Comment by zhouxiangwen328** [comment]
可以了谢谢
