### ISSUE TITLE
插件不能正常安装怎么处理

### ISSUE THREAD

**Issue by zhouxiangwen328** [Soulter/AstrBot#166]
![Screenshot_20240526_190915](https://github.com/Soulter/AstrBot/assets/163638679/c0fce41b-65fa-4869-93aa-6f3bc04e7f06)

**Comment by Soulter** [comment]
除了LLMS，装了其他插件嘛

**Comment by zhouxiangwen328** [comment]
https://github.com/Soulter/astrbot_plugin_telegram本来也想装这个也没装上,上面只有一个自带的插件

**Comment by Soulter** [comment]
是telegram插件的问题，最近更新了插件接口，telegram插件的一些接口没来得及更新。请在addons/plugins下把telegram那个文件夹删掉，然后重启程序，就可以使用llms了

**Comment by zhouxiangwen328** [comment]
好的谢谢

**Comment by zhouxiangwen328** [comment]
现在已经可以了
