### ISSUE TITLE
[Bug] 更新了最新版docker镜像以后对话会报错

### ISSUE THREAD

**Issue by linxp001** [Soulter/AstrBot#189]
### 发生了什么

提问后机器人无法回答，后台日志有报错

### 如何复现？

1.更新最新版docker镜像
2.在QQ频道里向机器人提问（私聊即可）
3.机器人无法回复内容

### AstrBot 版本与部署方式

 3.3.9 Docker

### 操作系统

Linux

### 额外信息

![aad4fd30987bfaf73ae77bcbb1c79571](https://github.com/user-attachments/assets/6ac87405-456f-4244-859e-8c52a35d731a)

### 你愿意提交 PR 吗？

- [ ] 是的，我愿意提交 PR!

### Code of Conduct

- [X] 我已阅读并同意遵守该项目的 [行为准则](https://docs.github.com/zh/site-policy/github-terms/github-community-code-of-conduct)。

**Comment by Soulter** [comment]
已在 v3.3.10 中被修复。
