### ISSUE TITLE
[Bug] [13:03:42| WARNING] [text_chat|openai_official.py:361]: OpenAI 请求异常：Error code: 400 - {'error': {'message': '8K max_tokens is only available when using beta api (set base_url="https://api.deepseek.com/beta")', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_request_error'}}。

### ISSUE THREAD

**Issue by kkl14** [Soulter/AstrBot#211]
### 发生了什么

纯小白，使用deepseek连接大模型，发送请求不成功，请求大佬指导

### 如何复现？

打开仪表盘
![8ec6037f09477efc910aa824a77c0491](https://github.com/user-attachments/assets/158368b5-b66f-4830-a3fa-534c2fa790ad)
这样配置，然后QQ尝试发送消息

### AstrBot 版本与部署方式

使用 Windows 启动器快速部署
 Napcat接入qq

### 操作系统

Windows

### 额外信息

![e956060a20d7c61fb7aa31f130694807](https://github.com/user-attachments/assets/87ecaa9a-f3fb-4757-9b4c-e3186d12e6dc)

### 你愿意提交 PR 吗？

- [ ] 是的，我愿意提交 PR!

### Code of Conduct

- [X] 我已阅读并同意遵守该项目的 [行为准则](https://docs.github.com/zh/site-policy/github-terms/github-community-code-of-conduct)。

**Comment by Soulter** [comment]
将 base_url 后面加一个 `/v1`

**Comment by kkl14** [comment]
增加后报错变了
![Uploading 15aa878d1da8e55fe40fc7c272c40349.png…]()

**Comment by Soulter** [comment]
> 增加后报错变了
> 
> ![Uploading 15aa878d1da8e55fe40fc7c272c40349.png…]()
> 
> 

你传的截图有问题，没法正常显示。不过我猜可以试着把max token调整到4000以下

**Comment by kkl14** [comment]
非常感谢你的帮助，成功解决了该问题
