### ISSUE TITLE
[Bug] Dashboard下载插件时状态问题

### ISSUE THREAD

**Issue by irorange27** [Soulter/AstrBot#217]
### 发生了什么

当我从 面板 下载插件时，所有插件（包括已经下载的）在前端都会显示正在加载。

![image](https://github.com/user-attachments/assets/c144dbb1-663a-4785-9aa4-e7e56fb60224)

特别是当网络状态不好的时候，加载时间很长会很明显。

### 如何复现？

1.  打开面板；
2.  在国内无代理环境进行插件下载；

### AstrBot 版本与部署方式

面板显示v3.3.17（是否可能存在面板版本不同步的问题？） linux源码部署 目前是最新源代码。

### 操作系统

Linux

### 额外信息

![image](https://github.com/user-attachments/assets/1921064d-4470-4e43-ad69-7976a5fd89df)

![image](https://github.com/user-attachments/assets/30cd4e7f-a306-41b5-85f1-78078b29dbda)

### 你愿意提交 PR 吗？

- [ ] 是的，我愿意提交 PR!

### Code of Conduct

- [X] 我已阅读并同意遵守该项目的 [行为准则](https://docs.github.com/zh/site-policy/github-terms/github-community-code-of-conduct)。

**Comment by Soulter** [comment]
这个是预期现象，这里的卡片是用 `v-for` 循环出来的，都引用了 `loading` 这个变量，之后可以优化一下。非代理下载缓慢暂时没有找到好的解决方案。之后在安装插件的时候可以加一个自动弹出 console 的输出，这样不会那么 "黑箱" 一些

**Comment by irorange27** [comment]
> 这个是预期现象，这里的卡片是用 `v-for` 循环出来的，都引用了 `loading` 这个变量，之后可以优化一下。非代理下载缓慢暂时没有找到好的解决方案。之后在安装插件的时候会自动弹出 console 的输出，这样不会那么 "黑箱" 一些

好的。

非代理下载的话我有想法。国内有很多 GitHub 的镜像站，比如 https://github-mirror.us.kg/ ，可以试着从镜像拉取？（先进行测速判断是否需要选择镜像）

**Comment by Soulter** [comment]
> > 这个是预期现象，这里的卡片是用 `v-for` 循环出来的，都引用了 `loading` 这个变量，之后可以优化一下。非代理下载缓慢暂时没有找到好的解决方案。之后在安装插件的时候会自动弹出 console 的输出，这样不会那么 "黑箱" 一些
> 
> 好的。
> 
> 非代理下载的话我有想法。国内有很多 GitHub 的镜像站，比如 https://github-mirror.us.kg/ ，可以试着从镜像拉取？（先进行测速判断是否需要选择镜像）

![image](https://github.com/user-attachments/assets/20c9cdfe-d57f-46bd-bf4e-5718a1b86170)

![image](https://github.com/user-attachments/assets/43a37e9f-1c4f-428f-afd4-dad5e21fd457)


将会在下个版本中支持该镜像下载插件。

**Comment by Soulter** [comment]
已修复
