### ISSUE TITLE
[Bug]对接lagrange发送图片失败

### ISSUE THREAD

**Issue by IZichenya** [Soulter/AstrBot#219]
### 发生了什么

lagrange把绝对目录识别成相对目录了，导致图片文件没找到
![9Z~)_ 0Z6$XCVZUMHEBS F8](https://github.com/user-attachments/assets/23a301f9-f781-4de9-b312-465bfe32e49d)
![D}A{8JKUS JCFT%4NUTQV)Q](https://github.com/user-attachments/assets/b3cad872-5dbc-4a51-80cc-8315a3663f24)

### 如何复现？

让AtrBot发送图片

### AstrBot 版本与部署方式

最新命令行

### 操作系统

Linux

### 额外信息

看图

### 你愿意提交 PR 吗？

- [ ] 是的，我愿意提交 PR!

### Code of Conduct

- [X] 我已阅读并同意遵守该项目的 [行为准则](https://docs.github.com/zh/site-policy/github-terms/github-community-code-of-conduct)。

**Comment by Soulter** [comment]
已修复
