### ISSUE TITLE
[Bug] ModuleNotFoundError: No module named 'openai._exceptions'

### ISSUE THREAD

**Issue by MidTerm-CN** [Soulter/AstrBot#221]
### 发生了什么

Python运行main.py时未找到module

### 如何复现？

git clone https://github.com/Soulter/AstrBot.git
cd AstrBot
python main.py

### AstrBot 版本与部署方式

直接使用命令行

### 操作系统

Windows

### 额外信息

G:\Open Source Project\AstrBot\util\t2i\strategies\network_strategy.py:50: SyntaxWarning: invalid escape sequence '\`'
  text = text.replace("`", "\`")
Traceback (most recent call last):
  File "G:\Open Source Project\AstrBot\main.py", line 8, in <module>
    from astrbot.bootstrap import AstrBotBootstrap
  File "G:\Open Source Project\AstrBot\astrbot\bootstrap.py", line 5, in <module>
    from astrbot.message.handler import MessageHandler
  File "G:\Open Source Project\AstrBot\astrbot\message\handler.py", line 18, in <module>
    from openai._exceptions import *
ModuleNotFoundError: No module named 'openai._exceptions'

### 你愿意提交 PR 吗？

- [ ] 是的，我愿意提交 PR!

### Code of Conduct

- [X] 我已阅读并同意遵守该项目的 [行为准则](https://docs.github.com/zh/site-policy/github-terms/github-community-code-of-conduct)。

**Comment by Soulter** [comment]
请问可以提供一下 openai 库的信息吗？
```
pip show openai
```




Soulter噬魂
***@***.***

**Comment by MidTerm-CN** [comment]
我不是python开发者 我需要怎么查看openai这个包的库信息

**Comment by MidTerm-CN** [comment]
Name: openai
Version: 0.27.8
Summary: Python client library for the OpenAI API
Home-page: https://github.com/openai/openai-python
Author: OpenAI
Author-email: support@openai.com

**Comment by Soulter** [comment]
使用终端输入 pip show openai 即可




Soulter噬魂
***@***.***

**Comment by Soulter** [comment]
版本太老了（最新版本是 1.55.2），可以使用 pip install -U openai 升级到最新版本




Soulter
***@***.***
