### ISSUE TITLE
[Bug] [11:29:51| ERROR] [manager.py:34]: 未找到适用于 qq_official(new_qq_official(QQ)_0) 平台适配器，请检查是否已经安装或者名称填写错误。已跳过。 

### ISSUE THREAD

**Issue by Mushan3420** [Soulter/AstrBot#223]
### 发生了什么

全新安装最新版，配置好以后，启动，测试QQ消息，提示该机器人去火星了，查看控制台日志，发现报错。
` [11:29:51| ERROR] [manager.py:34]: 未找到适用于 qq_official(new_qq_official(QQ)_0) 平台适配器，请检查是否已经安装或者名称填写错误。已跳过。 `

### 如何复现？

全新安装最新版，配置好以后，启动，测试QQ消息，提示该机器人去火星了，查看控制台日志，发现报错。

### AstrBot 版本与部署方式

3.4.0 手动部署 Ubuntu 24.04 LTS Python 3.12.3

### 操作系统

Linux

### 额外信息

![屏幕截图_15-12-2024_113425_astrbot euyyue com](https://github.com/user-attachments/assets/59651595-bff1-4fce-a163-8d711b7eb418)

### 你愿意提交 PR 吗？

- [ ] 是的，我愿意提交 PR!

### Code of Conduct

- [X] 我已阅读并同意遵守该项目的 [行为准则](https://docs.github.com/zh/site-policy/github-terms/github-community-code-of-conduct)。

**Comment by Soulter** [comment]
已修复
