### ISSUE TITLE
建议加入API2D中转key支持

### ISSUE THREAD

**Issue by wenyinos** [Soulter/AstrBot#77]
通过第三方访问openAI的接口，国内大部分地区可用，支持常用支付手段（价格为OpenAI官方1.5倍）

[https://api2d.com/wiki/doc](/url)

示例：[http://chat.wenyinos.com](/url)

**Comment by Mushan3420** [comment]
文档登录才能查看？

> 通过第三方访问openAI的接口，国内大部分地区可用，支持常用支付手段（价格为OpenAI官方1.5倍）
> 
> [https://api2d.com/wiki/doc](/url)
> 
> 示例：[http://chat.wenyinos.com](/url)

**Comment by wenyinos** [comment]
> 文档登录才能查看？
> 
> > 通过第三方访问openAI的接口，国内大部分地区可用，支持常用支付手段（价格为OpenAI官方1.5倍）
> > 
> > [https://api2d.com/wiki/doc](/url)
> > 
> > 示例：[http://chat.wenyinos.com](/url)
> 
> 

你用github登录一下就行了
