### ISSUE TITLE
发送消息到QQ频道失败，错误代码如下

### ISSUE THREAD

**Issue by niezhe** [Soulter/AstrBot#91]
```
[ERROR] (http.py:73)_handle_response    [botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/dms/12642659579995321122/messages, 错误代码: 500, 返回内容: {'code': 2000004, 'message': ''}, trace_id:2b51e778e0c3cee2566022ab8c99f037
[System-Error] 回复QQ消息失败
QQ频道API错误:

[ERROR] (http.py:73)_handle_response    [botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/dms/12642659579995321122/messages, 错误代码: 500, 返回内容: {'code': 2000004, 'message': ''}, trace_id:4eedd66a3d013f8854d5cc1c6cbb3186
[System-Error] 回复QQ消息失败
[ERROR] (http.py:73)_handle_response    [botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/dms/12642659579995321122/messages, 错误代码: 400, 返回内容: {'code': 50006, 'message': 'empty msg'}, trace_id:68060583931a10cd7675f39062fa4ef3
[System-Error] 回复QQ消息失败
```

**Comment by Soulter** [comment]
如何复现，每条消息都是这样吗

**Comment by louis26wq** [comment]
我看了下，我的第一个报错都是403，查了腾讯bot的文档，显示是 链接未报备。记得以前的代码能自动加空格，越过qq的链接审查

**Comment by louis26wq** [comment]
> 如何复现，每条消息都是这样吗
我也遇到了问题。
刚查看了下，我的第一个报错都是403，查了腾讯bot的文档，显示是 链接未报备。记得以前的代码能自动加空格，越过qq的链接审查



信息来源:
[1]: https://www.mayoclinic.org/diseases-conditions/mosquito-bites/symptoms-causes/syc-20375310 | https://www.mayoclinic.org/diseases-conditions/mosquito-bites/symptoms-causes/syc-20375310
[2]: https://www.zhihu.com/question/395254310 | https://www.zhihu.com/question/395254310

⌈1/20⌋
[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/dms/2063386131982814803/messages, 错误代码: 403, 返回内容: {'code': 304003, 'message': 'url not allowed'}, trace_id:85bb663956776bba6d777d632ce6f757
[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/dms/2063386131982814803/messages, 错误代码: 500, 返回内容: {'code': 2000004, 'message': ''}, trace_id:f4b2465b4ca361f23ff4ba022ceb7226
QQ频道API错误: 

[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/dms/2063386131982814803/messages, 错误代码: 500, 返回内容: {'code': 2000004, 'message': ''}, trace_id:f8f049d47b7285c619cc37aabe62a538
[ERROR]	(http.py:73)_handle_response	[botpy

**Comment by Soulter** [comment]
> > 如何复现，每条消息都是这样吗
> > 我也遇到了问题。
> > 刚查看了下，我的第一个报错都是403，查了腾讯bot的文档，显示是 链接未报备。记得以前的代码能自动加空格，越过qq的链接审查
> 
> 信息来源: [1]: https://www.mayoclinic.org/diseases-conditions/mosquito-bites/symptoms-causes/syc-20375310 | [https://www.mayoclinic.org/diseases-conditions/mosquito-bites/symptoms-causes/syc-20375310](https://%EE%80%80www.mayoclinic.org%EE%80%81/diseases-conditions/%EE%80%80mosquito-bites%EE%80%81/symptoms-%EE%80%80causes%EE%80%81/syc-20375310) [2]: https://www.zhihu.com/question/395254310 | https://www.zhihu.com/question/395254310
> 
> ⌈1/20⌋ [ERROR] (http.py:73)_handle_response [botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/dms/2063386131982814803/messages, 错误代码: 403, 返回内容: {'code': 304003, 'message': 'url not allowed'}, trace_id:85bb663956776bba6d777d632ce6f757 [ERROR] (http.py:73)_handle_response [botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/dms/2063386131982814803/messages, 错误代码: 500, 返回内容: {'code': 2000004, 'message': ''}, trace_id:f4b2465b4ca361f23ff4ba022ceb7226 QQ频道API错误:
> 
> [ERROR] (http.py:73)_handle_response [botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/dms/2063386131982814803/messages, 错误代码: 500, 返回内容: {'code': 2000004, 'message': ''}, trace_id:f8f049d47b7285c619cc37aabe62a538 [ERROR] (http.py:73)_handle_response [botpy

现在其实也会，在第一个报错之后程序就加空格并再次尝试发送了。第二个和第三个报错目前不知道是什么，我猜可能是内容超长了

**Comment by Soulter** [comment]
新的提交把频道的资料来源显示去掉了，应该可以解决这个问题。

**Comment by niezhe** [comment]
拉取了最新的代码，还是不行
这行代码报错了
```
asyncio.run_coroutine_threadsafe(message.reply(content=res), self.client.loop).result()
```


```

[QQCHAN-BOT] 接收到消息：python多线程的常用模块
[ChatGPT] Python多线程的常用模块有：

1. threading：Python标准库中的多线程模块，提供了Thread类、Lock类、Condition类、Semaphore类等多个并发编程的基本工具。

2. queue：Python标准库中的队列模块，提供了多线程之间安全传递数据的队列。

3. concurrent.futures：Python标准库中的异步执行模块，提供了ThreadPoolExecutor类和ProcessPoolExecutor类，可以实现线程池和进程池的高效并发执行。

4. multiprocessing：Python标准库中的多进程模块，提供了Process类、Queue类、Pipe类等多个并发编程的基本工具。

5. asyncio：Python标准库中的异步编程模块，提供了协程和事件循环机制，可以实现高效的并发IO操作。

6. greenlet：第三方库，提供了协程的实现和切换机制，可以用于实现高效的并发编程。

7. gevent：第三方库，基于greenlet实现的高效的异步编程框架，可以实现高并发的网络应用程序。
[System-Info] 回复QQ频道消息中...[GPT]Python多线程的常用模块有：

1. threading：Python标准库中的多线程模块，提供了Thread类、Lock类、Condition类、Semaphore类等多个并发编程的基本工具。

2. queue：Python标准库中的队列模块，提供了多线程之间安全传递数据的队列。

3. concurrent.futures：Python标准库中的异步执行模块，提供了ThreadPoolExecutor类和ProcessPoolExecutor类，可以实现线程池和进程池的高效并发执行。

4. multiprocessing：Python标准库中的多进程模块，提供了Process类、Queue类、Pipe类等多个并发编程的基本工具。

5. asyncio：Python标准库中的异步编程模块，提供了协程和事件循环机制，可以实现高效的并发IO操作。

6. greenlet：第三方库，提供了协程的实现和切换机制，可以用于实现高效的并发编程。

7. gevent：第三方库，基于greenlet实现的高效的异步编程框架，可以实现高并发的网络应用程序。
[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/dms/12642659579995321122/messages, 错误代码: 500, 返回内容: {'code': 2000004, 'message': ''}, trace_id:bae69bf4daf8844ae65bcb088c5a9a8f
QQ频道API错误: 

[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/dms/12642659579995321122/messages, 错误代码: 500, 返回内容: {'code': 2000004, 'message': ''}, trace_id:ffb642d71646d5e9dc3b15d3771842f2
[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/dms/12642659579995321122/messages, 错误代码: 500, 返回内容: {'code': 2000004, 'message': ''}, trace_id:699dd31fb2079c1eb9680c72b8df6062
回复消息错误: 
empty msg
[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/dms/12642659579995321122/messages, 错误代码: 400, 返回内容: {'code': 50006, 'message': 'empty msg'}, trace_id:b4af52de993474b572b5a091a45585b9
```

**Comment by xionghaizhi** [comment]
+1
